name: build carbon
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Atualizado para a versão 5 do actions/checkout
      - name: get python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: install bazelisk
        uses: bazelbuild/setup-bazelisk@v2  # Atualizado para a versão 3 do bazelbuild/setup-bazelisk
      - name: install llvm
        run: sudo apt-get update && sudo apt-get install -y llvm
      - name: build lol
        run: bazel build //explorer
      - name: upload built file
        uses: actions/upload-artifact@v3.1.0
        with:
          name: explorer
          path: bazel-bin/explorer/explorer
